export const pages =[
    '/basic-details',
    '/experience-details',
    '/education-details',
    '/certification-details'
]

export const years=(startYear, endYear)=> {
    const years = [];
    for (let year = startYear; year <= endYear; year++) {
        years.push(year);
    }
    return years;
}

export const techStackList=[
    "Python", 
    "Java",
    "C",
    "C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "Ruby",
    "PHP",
    "Swift",
    "Go (Golang)",
    "Rust",
    "Kotlin",
    "Dart",
    "R",
    "Shell (Bash)",
    "Scala",
    "Elixir",
    "Haskell",
    "Lua",
    "Perl",
    "Objective-C",
    "Groovy",
    "F#",
    "COBOL",
    "Fortran",
    "Assembly Language",
    "MATLAB",
    "Julia",
    "VB.NET",
    "ActionScript",
    "AWK",
    "Smalltalk",
    "Nim",
    "Crystal",
    "OCaml",
    "Erlang",
    "Hack",
    "Solidity",
    "Scheme",
    "Pascal",
    "Tcl",
    "Q#",
    "PureScript",
    "SAS",
    "D",
    "APL",
    "Forth",
    "Modula-2",
    "Bash",
    "HTML",
    "CSS",
    "Sass",
    "LESS",
    "Bootstrap",
    "Tailwind CSS",
    "React",
    "Angular",
    "Vue.js",
    "jQuery",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "ASP.NET",
    "Spring",
    "Laravel",
    "Symfony",
    "Phoenix",
    "GraphQL",
    "REST APIs",
    "Webpack",
    "Parcel",
    "Gulp",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Cassandra",
    "Oracle Database",
    "Microsoft SQL Server",
    "MariaDB",
    "DynamoDB",
    "Swift (iOS)",
    "Kotlin (Android)",
    "Java (Android)",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Apache Cordova",
    "Docker",
    "Kubernetes",
    "Ansible",
    "Terraform",
    "Jenkins",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "AWS (Amazon Web Services)",
    "Azure",
    "Google Cloud Platform",
    "Heroku",
    "OpenShift",
    "CI/CD",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Matplotlib",
    "Seaborn",
    "RStudio",
    "Apache Spark",
    "Hadoop",
    "Dask",
    "Unity",
    "Unreal Engine",
    "Godot",
    "Cocos2d",
    "CryEngine",
    "Processing",
    "Scratch",
    "OpenCL",
    "MATLAB Simulink",
    "VHDL",
    "Verilog",
    "CoffeeScript",
    "Dylan",
    "Eiffel",
    "NATJ",
    "REXX",
    "Io",
    "Seed7",
    "XSLT",
    "Vimscript",
    "PowerShell",
    "SQL",
    "PL/SQL",
    "ABAP",
    "FoxPro",
    "NATURAL",
    "Inform",
    "Simulink",
    "Pike",
    "Chapel",
    "Ring",
    "Red",
    "Ada",
    "MQL",
    "Bourne Shell",
    "Zig",
    "Squirrel",
    "Turing",
    "Common Lisp",
    "J",
    "AutoHotkey",
    "HTML5",
    "SVG",
    "WebAssembly",
    "PWA (Progressive Web Apps)",
    "AMP (Accelerated Mobile Pages)",
    "Gatsby",
    "Next.js",
    "Nuxt.js",
    "Sapper",
    "Deno",
    "Arduino",
    "Raspberry Pi",
    "MicroPython",
    "C for Embedded Systems",
    "ESP8266/ESP32",
    "Ethereum",
    "Hyperledger",
    "Corda",
    "Chaincode",
    "ALGOL",
    "Modula-3",
    "Fantom",
    "Oberon",
    "Simula",
    "Icon",
    "Vala",
    "Elm",
    "Racket",
    "Kotlin Multiplatform",
    "ReasonML",
    "ClojureScript",
    "Fennel",
    "Pony",
    "K"
]


